<div class="nav navbar align-items-center justify-content-between bg-dark" style="height:4rem">
    <h4 class="m-0 text-light">Editar Funcionário</h4>
    <h4 class="m-0 text-white"><i class="fas fa-user mr-2" style="font-size:28px"></i></h4>
</div>
<div class="d-flex align-items-center justify-content-center px-1" style="min-height: 91vh">
    <div class="py-4 px-3 card" style="width:30rem">
        <form action="/update_employee" class="text-secondary" method="post">
            <input type="hidden" name="id" value="<?= $_POST['id'] ?>">
            <div class="my-4">
                <label for="nome">Nome</label>
                <input type="text" name="nome" id="nome" class="form-control" size="60" placeholder="Nome" maxlength="60" value="<?= $_POST['nome'] ?>" required>
            </div>
            <div class="mb-4">
                <label for="cargo">Cargo</label>
                <input type="text" name="cargo" id="cargo" class="form-control mb-2" size="60" placeholder="Cargo" maxlength="60" value="<?= $_POST['cargo'] ?>" required>
            </div>
            <div class="d-flex justify-content-between">
                <div>
                    <label for="data_nascimento">Data de nascimento</label>
                    <input type="date" name="data_nascimento" id="data_nascimento" class="form-control" size="60" placeholder="Data de nascimento" maxlength="10" value="<?= $_POST['data_nascimento'] ?>" required>
                </div>
                <div>
                    <label for="data_admissao">Data de admissão</label>
                    <input type="date" name="data_admissao" id="data_admissao" class="form-control" size="60" placeholder="Data de admissão" maxlength="10" value="<?= $_POST['data_admissao'] ?>" required>
                </div>
            </div>
            <button type="submit" class="btn btn-info w-100 mt-5">Atualizar</button>
            <a href="/" class="btn btn-danger w-100 mt-2">Voltar</a>
        </form>
    </div>
</div>