<html>
	<head>
		<title>Loja teste</title>
		<meta charset="utf-8"/>
   		<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
		<meta name="viewport" content="width=device-width, initial-scale=1"/>
		<meta name="keywords" content=""/>
		<meta name="description" content=""/>
		<meta name="author" content="Guilherme Avelino"/>

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"/>
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous"/>
		
		<link rel="stylesheet" href="datatables/css/query.datatable.min.css" />
		<link rel="stylesheet" href="datatables/css/responsive.datatable.min.css" />
		<link rel="stylesheet" href="datatables/css/dataTables.bootstrap4.min.css" />
		
		<link rel="stylesheet" href="css/global.css"/>
		<link rel="stylesheet" href="css/index.css"/>
	</head>
	<body>
		<?= $this->content() ?>
	
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

		<script src="datatables/js/popper.js"></script>
		<script src="datatables/js/query-3.5.1.js"></script>
		<script src="datatables/js/jquery.dataTables.min.js"></script>
		<script src="datatables/js/datatable.responsive.js"></script>
		<script src="datatables/js/dataTables.bootstrap4.min.js"></script>
		<script src="datatables/js/datatable.js"></script>

		<script>
			$('#campo-data-admissao').hide();
			$("#select-categoria-export").change(function() {
				if (this.value == "Todos os funcionários") {
					$('#campo-data-admissao').hide();
				} else if (this.value == "Por data de admissão") {
					$('#campo-data-admissao').show();
				}
			});
		</script>
	</body>
</html>